---
# defaults file for libvirt
libvirt_libvirt_package_name: libvirt
libvirt_libvirt_service_name: libvirtd
libvirt_qemu_package_name: qemu-kvm
libvirt_storage_pool_name: default
libvirt_storage_pool_path: /var/lib/libvirt/images/
