galaxy_info:
  author: RaBe IT-Reaktion
  description: Install libvirt and configure storage pool.
  issue_tracker_url: https://github.com/radiorabe/ansible-collection-foreman-libvirt/issues
  license: AGPL-3.0-only
  min_ansible_version: '2.9'
  platforms:
    - name: EL
      versions:
        - all
    - name: Fedora
      version:
        - all
  galaxy_tags:
    - radiorabe
    - kvm
    - libvirt
    - qemu
dependencies: []
