---
exclude_paths:
  - .github/
  - venv/
skip_list:
  # We should start writing changelogs at some point
  - galaxy[no-changelog]
  # Ansible 2.14 on EL9 needs this for now
  - meta-runtime[unsupported-version]
