---
# tasks file for libvirt
- name: Ensure requirements are in place
  package:
    name:
      - "{{ libvirt_libvirt_package_name }}"
    state: present
  become: true

- name: Make sure libvirtd is enabled and started
  systemd_service:
    state: started
    enabled: true
    name: "{{ libvirt_libvirt_service_name }}"

- name: Write storage pool definition for {{ libvirt_storage_pool_name }}
  template:
      src: templates/storage-pool.xml.j2
      dest: /tmp/storage-pool.xml

- name: Create storage pool {{ libvirt_storage_pool_name }}
  command: virsh pool-create /tmp/storage-pool.xml

- name: Remove storage pool definition /tmp/storage-pool.xml
  file:
    path: /tmp/storage-pool.xml
    state: absent
