---
# tasks file for libvirt
- name: Ensure requirements are in place
  ansible.builtin.dnf:
    name:
      - "{{ libvirt_libvirt_package_name }}"
      - "{{ libvirt_qemu_package_name }}"
    state: present
  become: true

- name: Make sure libvirtd is enabled and started
  ansible.builtin.systemd:
    state: started
    enabled: true
    name: "{{ libvirt_libvirt_service_name }}"

- name: Check if storage pool exists {{ libvirt_storage_pool_name }}
  ansible.builtin.command: virsh pool-info {{ libvirt_storage_pool_name }}
  register: _libvirt_virsh_pool_info_result
  ignore_errors: true
  check_mode: true
  changed_when: true

- name: Define, create, configure, and start the storage pool {{ libvirt_storage_pool_name }}
  when: _libvirt_virsh_pool_info_results.rc
  block:
    - name: Write storage pool definition for {{ libvirt_storage_pool_name }}
      ansible.builtin.template:
        src: templates/storage-pool.xml.j2
        dest: /tmp/storage-pool.xml
        mode: "600"

    - name: Create storage pool {{ libvirt_storage_pool_name }}
      ansible.builtin.command: virsh pool-define /tmp/storage-pool.xml
      register: _libvirt_virsh_pool_define_results
      changed_when: "'defined' in _libvirt_virsh_pool_define_results.stdout"

    - name: Create storage pool directory {{ libvirt_storage_pool_path }}
      ansible.builtin.command: virsh pool-build {{ libvirt_storage_pool_name }}
      register: _libvirt_virsh_pool_build_results
      changed_when: "'built' in _libvirt_virsh_pool_build_results.stdout"

    - name: Set autostart in storage pool {{ libvirt_storage_pool_name }}
      ansible.builtin.command: virsh pool-autostart {{ libvirt_storage_pool_name }}
      register: _libvirt_virsh_pool_autostart_results
      changed_when: "'marked as autostarted' in _libvirt_virsh_pool_autostart_results.stdout"

    - name: Start storage pool {{ libvirt_storage_pool_name }}
      ansible.builtin.command: virsh pool-start {{ libvirt_storage_pool_name }}
      register: _libvirt_virsh_pool_start_results
      changed_when: "'started' in _libvirt_virsh_pool_start_results.stdout"

    - name: Remove storage pool definition /tmp/storage-pool.xml
      ansible.builtin.file:
        path: /tmp/storage-pool.xml
        state: absent
