---
# tasks file for libvirt
- name: Ensure requirements are in place
  ansible.builtin.package:
    name:
      - "{{ libvirt_libvirt_package_name }}"
    state: present
  become: true

- name: Make sure libvirtd is enabled and started
  ansible.builtin.systemd:
    state: started
    enabled: true
    name: "{{ libvirt_libvirt_service_name }}"

- name: Check if storage pool {{ libvirt_storage_pool_name }} already exists, do nothing if it does
  cansible.builtin.ommand: virsh pool-info {{ libvirt_storage_pool_name }}
  register: result
  ignore_errors: true

- name: Write storage pool definition for {{ libvirt_storage_pool_name }}
  ansible.builtin.template:
      src: templates/storage-pool.xml.j2
      dest: /tmp/storage-pool.xml
  when: result.rc != 0

- name: Create storage pool {{ libvirt_storage_pool_name }}
  ansible.builtin.command: virsh pool-define /tmp/storage-pool.xml
  when: result.rc != 0

- name: Create storage pool directory {{ libvirt_storage_pool_path }}
  ansible.builtin.command: virsh pool-build {{ libvirt_storage_pool_name }}
  when: result.rc != 0

- name: Set autostart in storage pool {{ libvirt_storage_pool_name }}
  ansible.builtin.command: virsh pool-autostart {{ libvirt_storage_pool_name }}
  when: result.rc != 0

- name: Start storage pool {{ libvirt_storage_pool_name }}
  ansible.builtin.command: virsh pool-start {{ libvirt_storage_pool_name }}
  when: result.rc != 0

- name: Remove storage pool definition /tmp/storage-pool.xml
  ansible.builtin.file:
    path: /tmp/storage-pool.xml
    state: absent
  when: result.rc != 0
