---
# tasks file for kvm_provision
- name: Ensure requirements in place
  delegate_to: "{{ cloudinit_image_preparation_host }}"
  package:
    name:
      - libguestfs-tools
    state: present
  become: true

- name: Download base image
  delegate_to: "{{ cloudinit_image_preparation_host }}"
  get_url:
    url: "{{ cloudinit_image_base_image_url }}"
    dest: "{{ cloudinit_image_local_files_path }}"
    checksum: "sha256:{{ cloudinit_image_base_image_sha }}"

- name: Configure the image
  delegate_to: "{{ cloudinit_image_preparation_host }}"
  command: |
    virt-customize -a {{ cloudinit_image_local_files_path }}/{{ cloudinit_image_base_image_name }} \
    --run-command "dnf install -y subscription-manager"

- name: Copy base image to libvirt storage pool directory {{ cloudinit_image_libvirt_pool_dir }}
  copy:
    dest: "{{ cloudinit_image_libvirt_pool_dir }}/"
    src: "{{ cloudinit_image_local_files_path }}/{{ cloudinit_image_base_image_name }}"
    force: no
    mode: 0660

- name: Ensure temporary file is deleted
  delegate_to: "{{ cloudinit_image_preparation_host }}"
  file:
    path: "/tmp/{{ cloudinit_image_base_image_name }}"
    state: absent
